go-kratos/go-kratos.dev

- docs/component/tracing.md
> writing tracing documents

- blog/2021-06-03-go-kratos-OpenTelemetry.md
- blog/2021-06-03-go-layout-operation-process.md
> reprint article

- i18n/en/docusaurus-plugin-content-docs/current/community/contribution.md
> docs: translate conventional commits

- docs/component/config.md
docs for go-kratos/kratos#1181
> docs(config): add env source docs

- docs/component/middleware/logging.md
在一些项目中只想打印trace_id，没有相关的采集服务器。
> 增加无需采集的数据但是打印trace_id的配置

- docs/component/config.md
- i18n/en/docusaurus-plugin-content-docs/current/community/contribution.md
由于：https://github.com/go-kratos/kratos/pull/1220 的提交 source 的加载循序不再被限制，所以修改对应的文档信息
---
squash and merge 进行合并
> docs: modify the behavior description of loading config source order

- docs/component/transport/grpc.md
- docs/component/transport/http.md
- i18n/en/docusaurus-plugin-content-docs/current/component/transport/grpc.md
- i18n/en/docusaurus-plugin-content-docs/current/component/transport/http.md
> fix: fix typo word

- docs/getting-started/plugin.md
> fix: update plugin.md

- docs/getting-started/04-examples.md
hello, there is something wrong on kube url, it is nacos
> fix discovery and registry example url

- docs/component/middleware/02-auth.md
- i18n/en/docusaurus-plugin-content-docs/current/component/middleware/02-auth.md
update white list example link
> feat(middleware/auth):change white list example link

- .github/workflows/gitee_sync.yml
Reverts go-kratos/go-kratos.dev#96
> Revert "rename gitee project name"

- docs/component/middleware/08-tracing.md
https://github.com/open-telemetry/opentelemetry-go/pull/2147
使用姿势更新
> feat upgrade tracing usage

- docs/component/middleware/02-auth.md
- i18n/en/docusaurus-plugin-content-docs/current/component/middleware/02-auth.md
add doc that show how to  use claim at server
> feat(middleware/auth):add claim doc

- docs/component/08-registry.md
- i18n/en/docusaurus-plugin-content-docs/current/component/08-registry.md
Description (what this PR does / why we need it):
docs: update registry.md
Which issue(s) this PR fixes (resolves / be part of):
Other special notes for reviewer:
> docs: update registry.md

- docs/component/08-registry.md
fix consul sample code import error
> fix registry

- docs/component/03-encoding.md
- i18n/en/docusaurus-plugin-content-docs/current/component/03-encoding.md
docs: modify zh and en of encoding.md.
> docs: modify encoding

- docs/component/09-selector.md
- i18n/en/docusaurus-plugin-content-docs/current/component/09-selector.md
> docs: update selector.md zh & en

- docs/component/middleware/04-logging.md
> @doc：修改grpc client代码示例

- i18n/en/docusaurus-plugin-content-docs/current/intro/01-overview.md
correct overview page some grammatical errors and improve readability
> 78 documentation difficult to understand due to grammatical errors

- docs/component/middleware/06-ratelimit.md
- i18n/en/docusaurus-plugin-content-docs/current/component/middleware/06-ratelimit.md
Ratelimit中英文文档更新
1. 代码tab调整为4空格
2. 中英文符号调整
3. 冗余字删除
4. demo增加自定义limiter使用说明
> docs: update 06-ratelimit.md zh & en

- docs/component/transport/02-http.md
- i18n/en/docusaurus-plugin-content-docs/current/component/transport/02-http.md
ref https://github.com/go-kratos/go-kratos.dev/issues/111
markdown lint
补充 server 以及 client 配置
> doc: update transport http

- i18n/en/docusaurus-plugin-content-docs/current/community/01-contribution.md
Add the Release example content && some content correction && Docs Format.
> docs: update EN Community‘s Contibution Guide Page

- docs/community/02-documentation.md
- i18n/en/docusaurus-plugin-content-docs/current/community/02-documentation.md
Ref #158 
Update to [Document Specification](https://go-kratos.dev/en/docs/community/documentation#document-specification) context.
> Docs: Update Community's Contribution Guide Page

- docs/devops/01-docker.md
- i18n/en/docusaurus-plugin-content-docs/current/devops/01-docker.md
upgrade Dockerfile go version to 1.16
> Docs:Update Deployment‘s Docker Page

- docs/component/middleware/01-overview.md
Update some content correction && docs format.
> Docs:Update middleware Overview Page

- docs/component/middleware/01-overview.md
- i18n/en/docusaurus-plugin-content-docs/current/component/middleware/01-overview.md
Update a new content && content correction
> Docs:Update En Middleware Overview Page

- docs/component/middleware/01-overview.md
fix Heading Level error && content correction && format correction
> Docs: fix Middleware Overview page error

- docs/component/transport/03-grpc.md
- docs/getting-started/02-usage.md
- i18n/en/docusaurus-plugin-content-docs/current/component/transport/03-grpc.md
ref https://github.com/go-kratos/go-kratos.dev/issues/111
[WeOpen Star] 更新文档错误代码用例、更新代码实现细节与最新代码不一致的问题
> docs:Update transporter grpc

- docs/guide/01-api-protobuf.md
- i18n/en/docusaurus-plugin-content-docs/current/guide/01-api-protobuf.md
Update `api/protobuf`  pages && Fix some outdated contents.
> Docs: update protobuf guideline pages

- docs/component/04-errors.md
> fix: 修复安装 protoc-gen-go-errors 命令错误

- blog/2021-06-03-go-layout-operation-process.md
> Fix: wrong proto dir

- docs/component/05-log.md
链接：
https://go-kratos.dev/docs/component/log
> 文档去掉多余的符号"、"

- docs/getting-started/04-examples.md
- i18n/en/docusaurus-plugin-content-docs/current/getting-started/04-examples.md
Update `getting-started/examples.md` to latest && correct some styles.
Solve #182.
> Docs: update getting-started/examples EN docs

- docs/component/09-selector.md
- i18n/en/docusaurus-plugin-content-docs/current/component/09-selector.md
Update  EN `component/selector.md` to sync with CN docs && correct some styles.
Solve  #184.
> Docs: Update component/selector EN docs.

- docs/intro/03-faq.md
- i18n/en/docusaurus-plugin-content-docs/current/intro/03-faq.md
添加「如何控制 http 返回 enum（枚举类型）的名称和数字」
> docs: 添加「如何控制 http 返回 enum（枚举类型）的名称和数字」

- docs/devops/01-docker.md
- i18n/en/docusaurus-plugin-content-docs/current/devops/01-docker.md
update new dockerfile in EN & CN docs.
> docs: update build go version in dockerfile

- docs/component/02-config.md
- i18n/en/docusaurus-plugin-content-docs/current/component/02-config.md
fix: #215 
话说 web 站这边修正个 typo 也要遵守 kratos 那边的流程吗？又 issue 又 pr 的好麻烦。
> fix: example code issue in 02-config #215

- docs/component/02-config.md
- i18n/en/docusaurus-plugin-content-docs/current/component/02-config.md
> doc: add comma to example code

- docs/component/05-log.md
log.DefaultLogged => log.DefaultLogger
> Update 05-log.md, fix clerical error

- docs/getting-started/02-usage.md
- i18n/en/docusaurus-plugin-content-docs/current/getting-started/02-usage.md
update `changelog dev` description to more easy understand.
> docs: update changelog dev description.

- docs/component/transport/03-grpc.md
- i18n/en/docusaurus-plugin-content-docs/current/component/transport/03-grpc.md
[about this issue](https://github.com/go-kratos/kratos/issues/3520)
> update component/transport/grpc.md add some client options instructions
